FROM node:18-bullseye-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install --production

COPY . .

EXPOSE 5000
CMD ["node", "src/index.js"]
